### ISSUE TITLE
RenderError crash on launch

### ISSUE THREAD

**Issue by ekgame** [fluddokt/opsu#1]
RenderError
OpsuAnd0.6.1c
Android 5.0.1 Nexus 5
java.lang.NullPointerException: Attempt to invoke virtual method 'int fluddokt.opsu.fake.UnicodeFont.getLineHeight()' on a null object reference
	at itdelatrisu.opsu.states.DownloadsMenu.init(DownloadsMenu.java:159)
	at fluddokt.opsu.fake.StateBasedGame.init(StateBasedGame.java:91)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:92)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by fluddokt** [comment]
That you for reporting this.

Can you try this?
https://github.com/fluddokt/opsu/releases/tag/0.6.1d

**Comment by ekgame** [comment]
Yes, it works now! Thank you for the update.

**Comment by fluddokt** [comment]
Alright thanks again, I would not have figured this out without this.

**Comment by DarkSVK123** [comment]
I have a problem with connection it says could not establish to server.

**Comment by fluddokt** [comment]
I'm guessing you are talking about the downloads. Which is currently default to bloodcat's server, which was down and should work now. Alternatively try clicking on the bloodcat button to try a different server.

**Comment by DarkSVK123** [comment]
I am sorry i forgot to change the download server. Now when i changed it
works normally.



  Thank you.

2015-09-26 2:13 GMT+02:00 fluddokt <notifications@github.com>:
