### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by shutbvs** [fluddokt/opsu#10]
RenderError
OpsuAnd0.7.0a
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    at itdelatrisu.opsu.states.Game.render(Game.java:204)
    at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:81)
    at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:120)
    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by fluddokt** [comment]
Seems like you are somehow trying to play a beatmap with no hitobjects...

Can I get some details on how you get this error?
Is it specific to one beatmap or does it always happen?
