### ISSUE TITLE
:

### ISSUE THREAD

**Issue by Gennadiyev** [fluddokt/opsu#100]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@84.0 AU@04.04.04.157.009 (CL@) (Qualcomm)
BOARD: G7-TL00
FINGERPRINT: Huawei/G7-TL00/hwG7-TL00:4.4.4/HuaweiG7-TL00/C01B252SP01:user/release-keys
HOST: huawei-desktop
MODEL: HUAWEI G7-TL00
INCREMENTAL: C01B252SP01
RELEASE: 4.4.4**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by Gennadiyev** [comment]
And where is the config map file path?

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.

config file should be in
 opsu/opsu.cfg
