### ISSUE TITLE
:

### ISSUE THREAD

**Issue by proudlytm** [fluddokt/opsu#101]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@  (GIT@Ifd751822f5) (Qualcomm)
BOARD: MSM8916
FINGERPRINT: motorola/harpia/harpia:6.0.1/MPI24.241-15.3/3:user/release-keys
HOST: phenom.zifnab.net
MODEL: Moto G Play
INCREMENTAL: 37da01c5b1
RELEASE: 7.1.1**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Gennadiyev** [comment]
Thqt was almost the same error i had yesterday

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
