### ISSUE TITLE
Failed to set current user in database.

### ISSUE THREAD

**Issue by MaxAvatar007** [fluddokt/opsu#109]
**Version:** 0.15.0a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r12p1-03dev0.92cea07ab1b80f9f42b782b097e01409 (ARM)
BOARD: universal8890
FINGERPRINT: samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQAS:user/release-keys
HOST: SWDD5923
MODEL: SM-G930F
INCREMENTAL: G930FXXU1DQAS
RELEASE: 7.0

**Error:** `Failed to set current user in database.`
**Stack trace:**
```
java.sql.SQLException: android.database.sqlite.SQLiteException: no such table: info (code 1): , while compiling: INSERT OR REPLACE INTO info VALUES ('user', ?)
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(no such table: info (code 1): , while compiling: INSERT OR REPLACE INTO info VALUES ('user', ?))
#################################################################
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at org.sqldroid.SQLDroidConnection.chainException(SQLDroidConnection.java:158)
	at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:147)
	at org.sqldroid.SQLDroidPreparedStatement.execute(SQLDroidPreparedStatement.java:190)
	at org.sqldroid.SQLDroidPreparedStatement.executeUpdate(SQLDroidPreparedStatement.java:222)
	at itdelatrisu.opsu.db.ScoreDB.setCurrentUser(ScoreDB.java:480)
	at itdelatrisu.opsu.user.UserList.changeUser(UserList.java:109)
	at itdelatrisu.opsu.user.UserList.<init>(UserList.java:78)
	at itdelatrisu.opsu.user.UserList.create(UserList.java:56)
	at itdelatrisu.opsu.Utils.init(Utils.java:182)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:108)
	at fluddokt.opsu.fake.StateBasedGame.init(StateBasedGame.java:143)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:100)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)
Caused by: android.database.sqlite.SQLiteException: no such table: info (code 1): , while compiling: INSERT OR REPLACE INTO info VALUES ('user', ?)
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(no such table: info (code 1): , while compiling: INSERT OR REPLACE INTO info VALUES ('user', ?))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1005)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:570)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1976)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1957)
	at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:140)
	... 13 more
```

**Comment by fluddokt** [comment]
Should be fixed in 0.15.0b
