### ISSUE TITLE
Could not create score database.

### ISSUE THREAD

**Issue by hermith** [fluddokt/opsu#11]
Nexus 9, Android 5.0

Could not create score database.
OpsuAnd0.8.0a
java.sql.SQLException: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
    at org.sqldroid.SQLDroidConnection.chainException(SQLDroidConnection.java:158)
    at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:170)
    at org.sqldroid.SQLDroidStatement.execute(SQLDroidStatement.java:96)
    at itdelatrisu.opsu.db.ScoreDB.createDatabase(ScoreDB.java:149)
    at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:96)
    at itdelatrisu.opsu.db.DBController.init(DBController.java:50)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:150)
    at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:92)
    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
    at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
    at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
    at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:163)
    ... 9 more

**Comment by fluddokt** [comment]
From what I could find on the Internet:
http://stackoverflow.com/questions/26937152/workaround-for-nexus-9-sqlite-file-write-operations-on-external-dirs
https://code.google.com/p/android/issues/detail?id=79994
This doesn't look like something I'm able to fix.
I guess you could wait and hope Android 5.1 fixes it.
Though you might be able to play still if you ignore the errors, however some functions of the app will not work.

**Comment by fluddokt** [comment]
Moved database to local (app)storage so should work in 0.14.0a.
