### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by RulyBogel** [fluddokt/opsu#135]
**Version:** 0.15.0b
**OS:** Linux (aarch64)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@05.01.00.115.099 (GIT@Ib5665b357a) (Qualcomm)
BOARD: msm8916
FINGERPRINT: OPPO/A37f/A37f:5.1.1/LMY47V/1480422943:user/release-keys
HOST: ubuntu-122-192
MODEL: A37f
INCREMENTAL: eng.root.20170110.092421
RELEASE: 5.1.1

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

**Comment by itdelatrisu** [comment]
This'll be fixed by the next release, sorry about that!  (itdelatrisu/opsu#254)
