### ISSUE TITLE
Error while downloading.

### ISSUE THREAD

**Issue by ccxex29** [fluddokt/opsu#14]
Error while downloading.
OpsuAnd0.8.0a
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at com.android.okio.Okio$2.read(Okio.java:113)
	at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
	at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
	at java.io.InputStream.read(InputStream.java:162)
	at java.nio.channels.Channels$InputStreamChannel.read(Channels.java:306)
	at itdelatrisu.opsu.downloads.ReadableByteChannelWrapper.read(ReadableByteChannelWrapper.java:53)
	at java.nio.FileChannelImpl.transferFrom(FileChannelImpl.java:400)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:221)

**Comment by chong601** [comment]
looks like a failed download for me... not really a biggie though

**Comment by fluddokt** [comment]
Should just give a warning since.0.11.0a.
