### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by perrottt** [fluddokt/opsu#143]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@  (GIT@I716aebe4f9) (Qualcomm)
BOARD: MSM8916
FINGERPRINT: samsung/gtelwifiue/gtelwifiue:5.1.1/LMY47X/T560NUUEU1AOH6:user/release-keys
HOST: SWHE0718
MODEL: SM-T560NU
INCREMENTAL: T560NUUEU1AOH6
RELEASE: 5.1.1

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by fluddokt** [comment]
Fixed in 0.16.0a
