### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by jamesguessis** [fluddokt/opsu#144]
Two issues, it won't download maps from any server, and if you keep trying you get a nice RenderError

**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 V@140.0 (GIT@Ifd751822f5) (Qualcomm)
BOARD: APQ8084
FINGERPRINT: motorola/quark_verizon/quark:6.0.1/MCG24.251-5-5/5:user/release-keys
HOST: ilclbld33
MODEL: XT1254
INCREMENTAL: 5
RELEASE: 6.0.1

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
