### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by TwojMagik** [fluddokt/opsu#148]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 (ARM)
BOARD: LYO-L01
FINGERPRINT: HUAWEI/LYO-L01/HWLYO-L6735:5.1/HUAWEILYO-L01/C150B128:user/release-keys
HOST: WUH1000003786
MODEL: HUAWEI LYO-L01
INCREMENTAL: C150B128
RELEASE: 5.1

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1592)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1295)
```

**Comment by fluddokt** [comment]
Fixed in 0.16.0a
