### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by Maka-Albarn** [fluddokt/opsu#164]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: unknown
FINGERPRINT: RCA/RCT6513W87/RCT6513W87:6.0/MRA58K/1469030504:user/release-keys
HOST: emdoor-OptiPlex-9020
MODEL: RCT6513W87
INCREMENTAL: 1471923235
RELEASE: 6.0

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
```

**Comment by Maka-Albarn** [comment]
Everytime I try to download a beatmap, it says that the download failed due to a connection error. I don't understand why it's doing this, I have an internet connection in my home and I'm connected, can you please help me with this problem? Thank you.

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
