### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by DanDanoPoP** [fluddokt/opsu#168]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: BalongV8R1SFT
FINGERPRINT: HONOR/CAM-L21/HWCAM-H:6.0/HUAWEICAM-L21/C223B131:user/release-keys
HOST: localhost#1
MODEL: CAM-L21
INCREMENTAL: C223B131
RELEASE: 6.0

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1544)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)
```

**Comment by fluddokt** [comment]
Fixed in 0.16.0a
