### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by ailiss** [fluddokt/opsu#170]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@I741a3d36ca) (Qualcomm)
BOARD: MSM8226
FINGERPRINT: htc/a56djul_00593/htc_a56djul:6.0.1/MMB29M/821993.1:user/release-keys
HOST: ABM108
MODEL: HTC Desire 10 lifestyle
INCREMENTAL: 821993.1
RELEASE: 6.0.1

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by fluddokt** [comment]
Fixed in 0.16.0a
