### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by rodrigezBCL** [fluddokt/opsu#18]
RenderError
OpsuAnd0.8.0a
java.lang.NullPointerException
	at itdelatrisu.opsu.states.Game.enter(Game.java:1063)
	at fluddokt.opsu.fake.StateBasedGame.enterNextState(StateBasedGame.java:56)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:91)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:120)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

**Comment by fluddokt** [comment]
This commit https://github.com/itdelatrisu/opsu/commit/6c956e927f8fa2b704914c70bae858f103542f97
probably fixed it, since it probably failed to create a HitObject causing the array to have less objects.
Or more like just throws a new Error message instead of being fixed.
