### ISSUE TITLE
WHEN DELETING ALL BEATMAP IN-GAME

### ISSUE THREAD

**Issue by flaze216** [fluddokt/opsu#184]
When I delete all of the beatmap using the client itself (not using the file manager), it crashes the game. Please make it redirect it to main menu when you deleted all of the beatmap instead of crashing the game.

LOG:

Run Date: Wed Jun 28 08:42:56 GMT+08:00 2017
Warn: Cannot find theme song [/storage/emulated/0/theme.mp3]. 
Error: ** Uncaught Exception! ** 
java.lang.NullPointerException: Attempt to read from field 'int itdelatrisu.opsu.beatmap.Beatmap.previewTime' on a null object reference
	at itdelatrisu.opsu.audio.MusicController.loopTrackIfEnded(MusicController.java:466)
	at itdelatrisu.opsu.states.SongMenu.update(SongMenu.java:842)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:122)
	at fluddokt.opsu.fake.GameOpsu.pause(GameOpsu.java:51)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:432)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by fluddokt** [comment]
Should be fixed in 0.16.0.a
