### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by alphaxmicka** [fluddokt/opsu#192]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: J608_PUBLIC
FINGERPRINT: DOOGEE/J608_PUBLIC/J608_PUBLIC:4.4.2/KOT49H/1416891008:user/dev-keys
HOST: 80-25
MODEL: KISSME-DG580
INCREMENTAL: eng.pengyinhua.1416891008
RELEASE: 4.4.2

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)
```

**Comment by fluddokt** [comment]
Fixed in 0.16.0a
