### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by Cuptaincapcake** [fluddokt/opsu#198]
**Version:** 0.15.0b
**OS:** Linux (x86_64)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: unknown
FINGERPRINT: RCA/RCT6873W42/RCT6873W42:6.0.1/MMB29M/hong07261054:user/release-keys
HOST: pb-server
MODEL: RCT6873W42
INCREMENTAL: eng.pb-server2.20160822.193207
RELEASE: 6.0.1

**Error:** `RenderError`
**Stack trace:**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:274)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:264)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:128)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:564)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1549)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1244)
```

**Comment by fluddokt** [comment]
Fixed in 0.16.0a
