### ISSUE TITLE
Could not save replay data.

### ISSUE THREAD

**Issue by To-mass** [fluddokt/opsu#204]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (Broadcom)
BOARD: hawaii
FINGERPRINT: samsung/kyleproxx/kylepro:4.2.2/JDQ39/S7580XXUBOA1:user/release-keys
HOST: SWDA2602
MODEL: GT-S7580
INCREMENTAL: S7580XXUBOA1
RELEASE: 4.2.2

**Error:** `Could not save replay data.`
**Stack trace:**
```
java.nio.charset.UnmappableCharacterException: Length: 1
	at java.nio.charset.CharsetEncoder.checkCoderResult(CharsetEncoder.java:325)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:290)
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:343)
```

**Comment by fluddokt** [comment]
Hopefully fixed in 0.16.0b
