### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by GreyMariGaming** [fluddokt/opsu#206]
**Version:** 0.16.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@145.0 AU@  (GIT@Ia3ef73d9d4) (Qualcomm)
BOARD: QC_Reference_Phone
FINGERPRINT: vivo/1606/1606:6.0.1/MMB29M/compiler08200057:user/release-keys
HOST: compiler026
MODEL: vivo 1606
INCREMENTAL: eng.compiler.20170820.005312
RELEASE: 6.0.1

**Error:** `RenderError`
**Stack trace:**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void fluddokt.opsu.fake.Graphics.setColor(fluddokt.opsu.fake.Color)' on a null object reference
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:372)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1839)
	at itdelatrisu.opsu.states.Game.render(Game.java:579)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by fluddokt** [comment]
fixed in 0.16.0b
