### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by ItzNetMidPower** [fluddokt/opsu#207]
**Version:** 0.16.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: aux
FINGERPRINT: Lenovo/aux/A850:4.2.2/JDQ39/A850_S203_140208.:user/release-keys
HOST: xmws46
MODEL: Lenovo A850
INCREMENTAL: A850_S203_140208
RELEASE: 4.2.2

**Error:** `RenderError`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:372)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1839)
	at itdelatrisu.opsu.states.Game.render(Game.java:579)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:129)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1550)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)
```

**Comment by fluddokt** [comment]
fixed in 0.16.0b
