### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by MONOPOSTOtm** [fluddokt/opsu#229]
**Version:** 0.16.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r3p0-00rel0.dce8ca6a85819d8495118734e2e3ccc6 (ARM)
BOARD: universal8895
FINGERPRINT: samsung/dreamltexx/dreamlte:7.0/NRD90M/G950FXXU1AQH3:user/release-keys
HOST: SWDG9810
MODEL: SM-G950F
INCREMENTAL: G950FXXU1AQH3
RELEASE: 7.0

**Error:** `RenderError`
**Stack trace:**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'itdelatrisu.opsu.beatmap.BeatmapSet itdelatrisu.opsu.beatmap.BeatmapSetNode.getBeatmapSet()' on a null object reference
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1791)
	at itdelatrisu.opsu.states.DownloadsMenu.update(DownloadsMenu.java:615)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:122)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:150)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)
```

**Comment by SuicidalTakis** [comment]
i got the same thing
