### ISSUE TITLE
RenderError Please help! When scrolling down settings, opsu! crashes.

### ISSUE THREAD

**Issue by perrottt** [fluddokt/opsu#238]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@Ia10634f51b) (Qualcomm)
BOARD: MSM8916
FINGERPRINT: samsung/gtelwifiue/gtelwifiue:6.0.1/MMB29M/T560NUUEU1BPF5:user/release-keys
HOST: SWHD4313
MODEL: SM-T560NU
INCREMENTAL: T560NUUEU1BPF5
RELEASE: 6.0.1

**Error:** `RenderError`
**Stack trace:**
```
java.lang.IllegalArgumentException: keycode cannot be negative, keycode: -1
	at com.badlogic.gdx.Input$Keys.toString(Input.java:248)
	at fluddokt.opsu.fake.Keyboard.getKeyName(Keyboard.java:13)
	at itdelatrisu.opsu.options.Options$GameOption$21.getValueString(Options.java:546)
	at itdelatrisu.opsu.options.OptionsOverlay.renderGenericOption(OptionsOverlay.java:857)
	at itdelatrisu.opsu.options.OptionsOverlay.renderOption(OptionsOverlay.java:751)
	at itdelatrisu.opsu.options.OptionsOverlay.renderOptions(OptionsOverlay.java:691)
	at itdelatrisu.opsu.options.OptionsOverlay.render(OptionsOverlay.java:510)
	at itdelatrisu.opsu.states.SongMenu.render(SongMenu.java:828)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:150)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1647)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1352)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
