### ISSUE TITLE
Failed to cancel download.

### ISSUE THREAD

**Issue by changeGithub** [fluddokt/opsu#246]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r12p1-04bet0.b125fee3fb58301c951089b9a402d362 (ARM)
BOARD: BND-AL10
FINGERPRINT: HONOR/BND-AL10/HWBND-H:7.0/HONORBND-AL10/C00B192:user/release-keys
HOST: shajk0108cna
MODEL: BND-AL10
INCREMENTAL: C00B192
RELEASE: 7.0

**Error:** `Failed to cancel download.`
**Stack trace:**
```
java.lang.IllegalStateException: Unbalanced enter/exit
	at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:62)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
	at com.android.okhttp.internal.Util.skipAll(Util.java:159)
	at com.android.okhttp.internal.Util.discard(Util.java:141)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:435)
	at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
	at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
	at java.nio.channels.Channels$ReadableByteChannelImpl.implCloseChannel(Channels.java:255)
	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:116)
	at itdelatrisu.opsu.downloads.ReadableByteChannelWrapper.close(ReadableByteChannelWrapper.java:45)
	at itdelatrisu.opsu.downloads.Download$2.run(Download.java:488)
```

**Comment by changeGithub** [comment]
and how can i play on other mode?
like osu!mania
thank you for your opsu!  
through i don't know more about development.

**Comment by Sodium-Aluminate** [comment]
there are only one mode （osu！） in opsu
opsu就一个模式啦
