### ISSUE TITLE
RenderError (on launch in Android 4.0.4)

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [fluddokt/opsu#25]
RenderError
OpsuAnd0.9.0a
java.lang.VerifyError: itdelatrisu/opsu/states/Game
	at itdelatrisu.opsu.Opsu.initStatesList(Opsu.java:94)
	at fluddokt.opsu.fake.StateBasedGame.init(StateBasedGame.java:120)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:99)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1513)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1267)

**Comment by fluddokt** [comment]
Assuming fixed somehow, since no new reports for 0.12.1a,
