### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by rodrigezBCL** [fluddokt/opsu#26]
RenderError
OpsuAnd0.9.0a
java.lang.NullPointerException
	at itdelatrisu.opsu.downloads.DownloadNode.drawDownload(DownloadNode.java:410)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:339)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:96)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:120)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

**Comment by fluddokt** [comment]
probably fixed https://github.com/itdelatrisu/opsu/issues/123
