### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by thecounterwolf** [fluddokt/opsu#261]
**Version:** 0.16.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@Ic280a69317) (Qualcomm)
BOARD: QC_Reference_Phone
FINGERPRINT: Xiaomi/santoni/santoni:7.1.2/N2G47H/V9.5.4.0.NAMMIFA:user/release-keys
HOST: mi-server
MODEL: Redmi 4
INCREMENTAL: V9.5.4.0.NAMMIFA
RELEASE: 7.1.2

**Error:** `RenderError`
**Stack trace:**
```
java.lang.IllegalArgumentException: keycode cannot be negative, keycode: -1
	at com.badlogic.gdx.Input$Keys.toString(Input.java:248)
	at fluddokt.opsu.fake.Keyboard.getKeyName(Keyboard.java:13)
	at itdelatrisu.opsu.options.Options$GameOption$22.getValueString(Options.java:556)
	at itdelatrisu.opsu.options.OptionsOverlay.renderGenericOption(OptionsOverlay.java:857)
	at itdelatrisu.opsu.options.OptionsOverlay.renderOption(OptionsOverlay.java:751)
	at itdelatrisu.opsu.options.OptionsOverlay.renderOptions(OptionsOverlay.java:691)
	at itdelatrisu.opsu.options.OptionsOverlay.render(OptionsOverlay.java:510)
	at itdelatrisu.opsu.states.SongMenu.render(SongMenu.java:828)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:134)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:150)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
