### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by tsunamiiii** [fluddokt/opsu#268]
**Version:** 0.16.1a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-02rel0.346006f07df626299db0815d6206ce13 (ARM)
BOARD: douglas
FINGERPRINT: Amazon/douglas/douglas:5.1.1/LVY48F/50.6.1.2_user_612496620:user/release-keys
HOST: i3-ri-14-use1a-b-93
MODEL: KFDOWI
INCREMENTAL: 50.6.1.2_user_612496620
RELEASE: 5.1.1

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException: Attempt to write to field 'boolean fluddokt.opsu.fake.AudioDevicePlayer2$PlayThread.toStop' on a null object reference
	at fluddokt.opsu.fake.AudioDevicePlayer2.stopThread(AudioDevicePlayer2.java:316)
	at fluddokt.opsu.fake.AudioDevicePlayer2.pause(AudioDevicePlayer2.java:378)
	at fluddokt.opsu.fake.MusicJL3.pause(MusicJL3.java:101)
	at fluddokt.opsu.fake.Music.pause(Music.java:57)
	at fluddokt.opsu.fake.Music$2.run(Music.java:213)
```

**Comment by kairusds** [comment]
The beatmap should not be anything like osu!mania or etc. since the client only supports standard types.
