### ISSUE TITLE
Error while downloading.

### ISSUE THREAD

**Issue by harmonyshammy** [fluddokt/opsu#27]
Error while downloading.
OpsuAnd0.9.0a
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:283)
	at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)
	at java.io.InputStream.read(InputStream.java:162)
	at java.nio.channels.Channels$InputStreamChannel.read(Channels.java:306)
	at itdelatrisu.opsu.downloads.ReadableByteChannelWrapper.read(ReadableByteChannelWrapper.java:53)
	at java.nio.FileChannelImpl.transferFrom(FileChannelImpl.java:396)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:221)

**Comment by chong601** [comment]
You can safely ignore the error since the error is about failed to download (server timed out) because of bad network connection.

(but it should be caught and then given proper error notification rather than spewing error to the user)

**Comment by fluddokt** [comment]
Should just give a warning since.0.11.0a.
