### ISSUE TITLE
Failed to save score to database.

### ISSUE THREAD

**Issue by alexisotaku** [fluddokt/opsu#29]
Failed to save score to database.
OpsuAnd0.9.0a
java.sql.SQLException: android.database.sqlite.SQLiteException: table scores has 19 columns but 18 values were supplied (code 1): , while compiling: INSERT INTO scores VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.sqldroid.SQLDroidConnection.chainException(SQLDroidConnection.java:158)
	at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:147)
	at org.sqldroid.SQLDroidPreparedStatement.execute(SQLDroidPreparedStatement.java:190)
	at org.sqldroid.SQLDroidPreparedStatement.executeUpdate(SQLDroidPreparedStatement.java:222)
	at itdelatrisu.opsu.db.ScoreDB.addScore(ScoreDB.java:225)
	at itdelatrisu.opsu.states.Game.updateGame(Game.java:731)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:1585)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:1568)
	at itdelatrisu.opsu.states.Game.update(Game.java:657)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:95)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:120)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
Caused by: android.database.sqlite.SQLiteException: table scores has 19 columns but 18 values were supplied (code 1): , while compiling: INSERT INTO scores VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:892)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:503)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1773)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1754)
	at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:140)
	... 12 more

**Comment by fluddokt** [comment]
Please uninstall 0.9.0a
