### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by ayanokouj** [fluddokt/opsu#294]
**Version:** 0.16.1a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@84.0 AU@05.00.00.002.025 (CL@) (Qualcomm)
BOARD: MSM8974
FINGERPRINT: samsung/hltelgt/hltelgt:5.0/LRX21V/N900LKLU0GPC4:user/release-keys
HOST: SWHD4306
MODEL: SM-N900L
INCREMENTAL: N900LKLU0GPC4
RELEASE: 5.0

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int itdelatrisu.opsu.beatmap.HitObject.getTime()' on a null object reference
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:138)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:2006)
	at itdelatrisu.opsu.states.SongMenu.access$11(SongMenu.java:1994)
	at itdelatrisu.opsu.states.SongMenu$5.run(SongMenu.java:1783)
```

**Comment by osuplayer2423** [comment]
wow free code lmao
