### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by TATARIN1997** [fluddokt/opsu#32]
** Uncaught Exception! **
OpsuAnd0.11.0a
java.lang.NoSuchMethodError: org.json.JSONObject.keySet
	at itdelatrisu.opsu.downloads.servers.YaSOnlineServer.resultList(YaSOnlineServer.java:148)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:210)
	at java.lang.Thread.run(Thread.java:838)

**Comment by fluddokt** [comment]
Should be fixed in the 0.12.1a
