### ISSUE TITLE
RenderError

### ISSUE THREAD

**Issue by Okamiwolf144** [fluddokt/opsu#4]
RenderError
OpsuAnd0.6.1d
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at itdelatrisu.opsu.downloads.DownloadList.getNode(DownloadList.java:62)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:287)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:81)
	at fluddokt.opsu.fake.GameOpsu.render(GameOpsu.java:106)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1525)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)

**Comment by Okamiwolf144** [comment]
This error pops up everytime I download and import a new song. :/

**Comment by fluddokt** [comment]
Thanks, can you try the lastest release and see if that works?
