### ISSUE TITLE
Failed to load replay data.

### ISSUE THREAD

**Issue by flazep3** [fluddokt/opsu#78]
Failed to load replay data.
OpsuAnd0.13.0a
java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:77)
	at itdelatrisu.opsu.io.OsuReader.readByte(OsuReader.java:76)
	at itdelatrisu.opsu.replay.Replay.loadHeader(Replay.java:159)
	at itdelatrisu.opsu.replay.Replay.load(Replay.java:137)
	at itdelatrisu.opsu.states.GameRanking.mousePressed(GameRanking.java:188)
	at fluddokt.opsu.fake.StateBasedGame.mousePressed(StateBasedGame.java:247)
	at fluddokt.opsu.fake.StateBasedGame.touchDown(StateBasedGame.java:227)
	at com.badlogic.gdx.InputMultiplexer.touchDown(InputMultiplexer.java:90)
	at com.badlogic.gdx.backends.android.AndroidInput.processEvents(AndroidInput.java:356)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:420)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)

**Comment by itdelatrisu** [comment]
Is this related to #79 or a different replay?

**Comment by ilhamdkk** [comment]
Blank screan to load beatmap android5.0

**Comment by fluddokt** [comment]
Guessing related to #79 in failing to save the replay.
