### ISSUE TITLE
:

### ISSUE THREAD

**Issue by slasher169** [fluddokt/opsu#83]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: sp7731gea_k11_qhd_zx_64_8
FINGERPRINT: SKK/scx35_sp7731gea_k11_qhd_skk_64_8:5.1/LMY47D/201606131753:user/release-keys
HOST: server12
MODEL: Chronos Cross
INCREMENTAL: 201606131753
RELEASE: 5.1**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
