### ISSUE TITLE
:

### ISSUE THREAD

**Issue by senketsu22** [fluddokt/opsu#86]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: smdk4x12
FINGERPRINT: samsung/p4noterfxx/p4noterf:4.4.2/KOT49H/N8000XXUDNL1:user/release-keys
HOST: SWDD5807
MODEL: GT-N8000
INCREMENTAL: N8000XXUDNL1
RELEASE: 4.4.2**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
