### ISSUE TITLE
:

### ISSUE THREAD

**Issue by bushona** [fluddokt/opsu#88]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@  (GIT@Iac7c2e2837) (Qualcomm)
BOARD: msm8909
FINGERPRINT: lge/m1_spr_us/m1:5.1.1/LMY47V/1605612535479:user/release-keys
HOST: LGEACI5R3
MODEL: LGLS675
INCREMENTAL: 1605612535479
RELEASE: 5.1.1**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
