### ISSUE TITLE
Could not save replay data.

### ISSUE THREAD

**Issue by koralli** [fluddokt/opsu#90]
Could not save replay data.
OpsuAnd0.13.0a
java.nio.charset.UnmappableCharacterException: Length: 1
	at java.nio.charset.CharsetEncoder.checkCoderResult(CharsetEncoder.java:282)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:263)
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:339)

**Comment by fluddokt** [comment]
Hopefully fixed in 0.16.0b
