### ISSUE TITLE
I like Opsu, this sucks

### ISSUE THREAD

**Issue by Battlesconrs** [fluddokt/opsu#93]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r12p1-00dev0.60546d7cd0bfd82d0ba92ca3bb825c75 (ARM)
BOARD: universal8890
FINGERPRINT: samsung/heroltexx/herolte:6.0.1/MMB29K/G930FXXU1BPLB:user/release-keys
HOST: SWHD7406
MODEL: SM-G930F
INCREMENTAL: G930FXXU1BPLB
RELEASE: 6.0.1**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
