### ISSUE TITLE
:bugs

### ISSUE THREAD

**Issue by Pazdziernik11** [fluddokt/opsu#95]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@136.0 AU@ (GIT@I3193f6e94a) (Qualcomm)
BOARD: msm8916
FINGERPRINT: lge/g4stylusn_global_com/g4stylusn:6.0/MRA58K/162021810898e:user/release-keys
HOST: LGEACI5R13
MODEL: LG-H635
INCREMENTAL: 162021810898e
RELEASE: 6.0**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by Pazdziernik11** [comment]
Bugs

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
