### ISSUE TITLE
:

### ISSUE THREAD

**Issue by nakuraP** [fluddokt/opsu#96]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (aarch64)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 (ARM)
BOARD: full_oppo6750_16321
FINGERPRINT: OPPO/CPH1605/CPH1605:5.1/LMY47I/1471871662:user/release-keys
HOST: WX-122-112
MODEL: CPH1605
INCREMENTAL: 1482157400
RELEASE: 5.1**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
