### ISSUE TITLE
:

### ISSUE THREAD

**Issue by HmFlashy** [fluddokt/opsu#97]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@I8b257659a0) (Qualcomm)
BOARD: QC_Reference_Phone
FINGERPRINT: OnePlus/OnePlus3/OnePlus3:7.0/NRD90M/12311011:user/release-keys
HOST: ubuntu-23
MODEL: ONEPLUS A3003
INCREMENTAL: 97
RELEASE: 7.0**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
