### ISSUE TITLE
:

### ISSUE THREAD

**Issue by kilometerman** [fluddokt/opsu#98]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@I37ca06bd2c) (Qualcomm)
BOARD: msm8996
FINGERPRINT: lge/h1_spr_us/h1:7.0/NRD90U/1630915177709:user/release-keys
HOST: LGEACI8R8
MODEL: LGLS992
INCREMENTAL: 1630915177709
RELEASE: 7.0**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
