### ISSUE TITLE
:i cant download new songs on Android 6.0

### ISSUE THREAD

**Issue by RexRed6802** [fluddokt/opsu#99]
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@I3f4bae6ca5) (Qualcomm)
BOARD: MSM8974
FINGERPRINT: Sony/D6503/D6503:6.0.1/23.5.A.0.575/1719295681:user/release-keys
HOST: BuildHost
MODEL: D6503
INCREMENTAL: 1719295681
RELEASE: 6.0.1**Error:** `:`
**Stack trace:**
```
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:495)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:223)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by aizawa-naoki** [comment]
Me,too. And I got errors like yours, but I can download from other website.
So maybe you can!ʕ•̀ω•́ʔ✧

`:
OpsuAnd0.13.0a
org.json.JSONException: Value Uncaught of type java.lang.String cannot be converted to JSONArray
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONArray.<init>(JSONArray.java:96)
	at org.json.JSONArray.<init>(JSONArray.java:108)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:454)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:80)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:219)
	at java.lang.Thread.run(Thread.java:841)`

**Comment by fluddokt** [comment]
Bloodcat download server was down, Seems to be back up. 0.15.0a shouldn't throw this Error anymore.
